### ISSUE TITLE
Newsletter Input + Button zerschießen die Mobile-Ansicht im Firefox

### ISSUE THREAD

**Issue by nanoparsec** [innoq/innoq-styleguide#29]
https://gitlab.innoq.com/innoq/innoq.com-cms/issues/852
<img width="422" alt="bildschirmfoto_2018-11-19_um_12 00 03" src="https://user-images.githubusercontent.com/1646402/50781255-31727800-12a5-11e9-9fc1-32bdecf86c6a.png">

**Comment by blynx** [comment]
Resolved by now. ✨
