### ISSUE TITLE
Buttons for Magenta Background

### ISSUE THREAD

**Issue by gataka** [innoq/innoq-styleguide#31]
Hello Style-Guide-Team

I'm currently working with the style guide from the innoq.com page (https://innoq.style) and I found that there is no button, which can be good used with the magenta background (`*--colored`). It should be something like the `btn--inverted` but with a blue `:hover`, otherwise you cannot see the hover color. 

Is this combination not allowed/expected or just not made? Can you please add this combintion to the style?

Thanks. 
Br
Philipp

**Comment by nanoparsec** [comment]
Hey,
at the moment we need only the buttons that are displayed in the style guide so we are not planning to add elements we do not need.
