### ISSUE TITLE
Button classes undefined

### ISSUE THREAD

**Issue by youngbrioche** [innoq/innoq-styleguide#48]
Some button component examples have unexpected class names: `btn--undefined`

![image](https://user-images.githubusercontent.com/3011/74445328-80aab500-4e76-11ea-8bcf-3595f1186d3e.png)

**Comment by nanoparsec** [comment]
Die complate Makros wurden mit e847f7394093e0f6c1fac8f85b6468b69f76e426 wieder aus dem Styleguide entfernt.
